Added README file
HovorukhaBohdan/book-shop pull request #18
Opened 2024-01-10 14:47 UTC by HovorukhaBohdan

2024-01-11 09:07 UTC, d1sam requested changes
Good job, but there are some improvements should be done!

2024-01-11 09:07 UTC, d1sam commented on README.md
> +## 🚀 ___Getting Started___ 🚀
what about docker-compose? )

2024-01-11 09:07 UTC, d1sam commented on README.md
> ++ ***Maven***
please provide categories, that technologies related to.

2024-01-11 09:07 UTC, d1sam commented on README.md
Don't forget to mention any challenges you faced and how you overcame them.

2024-01-11 09:07 UTC, d1sam commented on README.md
please also add Possible improvements section.

2024-01-16 06:49 UTC, yevheniisynytsia approved these changes
Well done! I left a minor comment, please address it

2024-01-16 06:49 UTC, yevheniisynytsia commented on README.md
> -5. **Exploring the API: Access the API documentation through Swagger, available at http://localhost:8080/swagger-ui.html: http://localhost:8080/swagger-ui.html.**
Let's leave the swagger link
it is useful for reviewing your project

2024-01-26 13:11 UTC, merged