Added GlobalExceptionHandler, fixed Book model field annotations, changed BookSearchParametersDto from record to class and changed methods for BookSpecificationBuilder
HovorukhaBohdan/book-shop pull request #5
Opened 2023-12-11 11:06 UTC by HovorukhaBohdan

2023-12-11 15:20 UTC, MinoDentori approved these changes
Good job!

2023-12-12 10:45 UTC, d1sam requested changes
Good job, but please look at my comments and make correct pr to see only changes for this hw :)

2023-12-12 10:45 UTC, d1sam commented on src/main/java/com/example/bookshop/dto/BookSearchParametersDto.java
this homework does not require any changes to this file.

2023-12-12 10:45 UTC, d1sam commented on src/main/java/com/example/bookshop/repository/book/BookSpecificationBuilder.java
this homework does not require any changes to this file.

2023-12-12 10:45 UTC, d1sam commented on src/main/java/com/example/bookshop/model/Book.java
this homework does not require any changes to this file.

2023-12-12 10:45 UTC, d1sam commented on src/main/java/com/example/bookshop/exception/CustomGlobalExceptionHandler.java
try to avoid String literals

2023-12-12 10:45 UTC, d1sam commented on src/main/java/com/example/bookshop/dto/UpdateBookRequestDto.java
provide messages to your dto-constraints :)

2023-12-12 10:45 UTC, d1sam commented on src/main/java/com/example/bookshop/dto/CreateBookRequestDto.java
provide messages to your dto-constraints :)

2023-12-13 07:00 UTC, kshuryhin requested changes
Good job, just one point to consider

2023-12-13 07:00 UTC, kshuryhin commented on src/main/java/com/example/bookshop/dto/CreateBookRequestDto.java
> +    @NotNull(message = "can't be null")
I guess we need also specify in the message, which particular field caused an error, what do you think?

2023-12-13 15:52 UTC, vovasalyha approved these changes
LGTM

2023-12-13 16:27 UTC, merged